name: nock
description: HTTP requests mocking library for dart and flutter. Test your application in isolation.
version: 1.0.1+1
homepage: https://github.com/cah4a/dart_nock

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  test: ^1.6.0
  collection: ^1.14.0

dev_dependencies:
  http: any
  pedantic: any
